### ISSUE TITLE
Strip it all

### ISSUE THREAD

**Issue by R4Z0R49** [R4Z0R49/DayZStats#1]
Strip everything to be left with just stats and info window for he players.

**Comment by Marcuzz** [comment]
Affirmative! I will do this when I get home

**Comment by R4Z0R49** [comment]
Marcuzz, i forgot to add you back to the admin tool when i moved i am sorry that was my fault :-(.

i've added both you and wirley to this and the admin tool again :-)

**Comment by R4Z0R49** [comment]
This is to be just stats and info.

**Comment by Marcuzz** [comment]
Yea. That is alright. And yea I think I know what to do here

**Comment by Marcuzz** [comment]
Alright, the main cleanup process is done, there might be code here and there but we'll remove that as we go.
There are some stuff regarding the leaderboard that's not functioning properly at the moment though, those being
-Distance traveled 
and
-Duration

Also, I am not sure what you wanted to do with info.php. But it looks like what you want to do wouldn't work entirely like that, hehe.
Do you want the users name on the leaderboard to lead to the users stats, like when you search for a user on the main stats page?

**Comment by R4Z0R49** [comment]
yes. info should show the old info page for the char giving detailed info about that player inventory backpack all that but no location.

i also get this error 
Warning: Invalid argument supplied for foreach() in /var/www/vhosts/sabretechlabs.com/httpdocs/DayZStats/modules/leaderboard.php on line 50 Fatal error: Call to a member function RecordCount() on a non-object in /var/www/vhosts/sabretechlabs.com/httpdocs/DayZStats/modules/leaderboard.php on line 55

**Comment by Marcuzz** [comment]
Alright, I'll work on that if Wriley doesn't do that.

That error is strange, are you sure everythings up to date? Because that doesn't happen for me. Well, it used to when I was testing it, thought now it doesn't happen :S

How is your database saving deaths? Mine seems to not save them anywhere, so I have to count the rows of dead people in Character_DEAD. But if they're supposed to save in say, Player_DATA then that is an easy thing to fix

Do you mind adding me on skype? ( Flamingsword90 ) - So that we don't have to spam the issues section of this. It'll become quite a wall of text, and response times are not always instant :)
-Unless of course, you prefer this.

**Comment by R4Z0R49** [comment]
yep removed and reinstalled get the same error.

**Comment by R4Z0R49** [comment]
```
                    /*
                    foreach($result2 as $row2){
                        $distanceFoot = $row2['distanceFoot'];
                        $duration = $row2['duration'];
                    }
                    */
```

and changed

$deaths = $rowl['Generation'] - 1;
                        echo "<tr>
                              <td>{$rank}</td>
                              <td>{$rowl['playerName']}</td>
                              <td>{$rowl['KillsZ']}</td>
                              <td>{$rowl['KillsH']}</td>
                              <td>{$rowl['KillsB']}</td>
                              <td>{$rowl['HeadshotsZ']}</td>
                              <td>{$rowl['Humanity']}</td>
                              <td>{$deaths}</td>
                              <td>{$row2['$distanceFoot']}</td>
                              <td>{$row2['$duration']} Minutes</td>
                              <td>{$points}</td>
                              </tr>";
                        $rank++;

everything but duration and distanceFoot is working

**Comment by R4Z0R49** [comment]
oh yea skype two secs

**Comment by Marcuzz** [comment]
Oh yeah, sorry, forgot about Generation being deaths, or spawns rather

**Comment by Marcuzz** [comment]
I think we can say that this issue can be closed.
