### ISSUE TITLE
Challenge a friend feature

### ISSUE THREAD

**Issue by Marcuzz** [R4Z0R49/DayZStats#2]
Ability to register, log in and create a leaderboard where only certain players, or friends if you will are included. This allows to compete with your friends

**Comment by Marcuzz** [comment]
Started work on this feature, registration / login / logout system is now finished. Sorry it's taking a while. Got some studies to finish before christmas, etc.

Other fixes in next revision:
- Background pattern now shows, accidentally removed.
- Fixed a few design errors

TODO:
- Finish the actual challenge a friend system
- Finish change password, player id, etc(Profile options)

**Comment by R4Z0R49** [comment]
Its no worrys, that time of the year for everyone

**Comment by Marcuzz** [comment]
Update:
- Finished profile settings

TODO:
- Start/Finish the challenge a friend / challenge friends system

EDIT:
- I have started work on the challenge friends feature, and so far I have made the pages, but not the MySQL part of it

**Comment by Marcuzz** [comment]
Done da1652f
